services:
  db:
    hostname: db
    image: pgvector/pgvector:pg16
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=aipo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
  tesseract-service:
    container_name: tesseract-ocr-container
    build:
      context: tesseract-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./tesseract-service:/app
